#!/usr/bin/env coman-bash
#SBATCH --time=24:00:00
#SBATCH --partition=regular
#SBATCH --cpus-per-task=1
#SBATCH --mem=80000
#SBATCH --output=logs/%x-%j.log
#SBATCH --mail-type=ALL
#SBATCH --mail-user=wietse.de.vries@rug.nl

bash train "$@" --dry_run
