#!/usr/bin/env coman-bash
#SBATCH --time=24:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --cpus-per-task=1
#SBATCH --mem=10000
#SBATCH --output=logs/%x-%j.log
#SBATCH --mail-type=ALL
#SBATCH --mail-user=wietse.de.vries@rug.nl

model_id=$1
model_type=$2

bash train xtreme \
    --seed=978234 \
    --language_train=en \
    --task_type=text-classification \
    --task_name=multinli \
    --model_id=$model_id \
    --model_type=$model_type \
    --lr_scheduler_type=linear \
    --learning_rate=5e-05 \
    --warmup_steps=500 \
    --eval_steps=500 \
    --logging_steps=100 \
    --gradient_accumulation_steps=2 \
    --per_device_train_batch_size=30 \
    --per_device_eval_batch_size=60 \
    --num_train_epochs=2 \
    --weight_decay=0.1
